# Generated by Django 4.1.1 on 2022-09-15 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_task_name_alter_task_time_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_limits',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 15, 1, 13, 9, 68877), verbose_name='Fecha de entrega'),
        ),
    ]
