# Generated by Django 4.1.1 on 2022-09-17 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_alter_task_time_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_limits',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 23, 25, 40, 238069), verbose_name='Fecha de ingreso'),
        ),
    ]
