# Generated by Django 4.1.1 on 2022-09-17 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_task_time_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_limits',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 23, 26, 17, 103657), verbose_name='Fecha de ingreso'),
        ),
    ]
